services:
  backend:
    build: backend_app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - backend_app/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=task_management_db
    networks:
      - appnet
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - appnet
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend_app/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
